// src/components/sidebar/ProviderList.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import SidebarSection from './SidebarSection.vue'
import ProviderDropdown from './ProviderDropdown.vue'
import { SIDEBAR_KEY } from './context'

const sidebar = inject(SIDEBAR_KEY)!
const paneIndices = computed(() =>
  Array.from({ length: sidebar.paneCount.value }, (_, paneIndex) => paneIndex)
)
</script>

<template>
  <SidebarSection title="PROVIDERS">
    <div class="provider-list">
      <div
        v-for="paneIndex in paneIndices"
        :key="paneIndex"
        class="provider-item"
      >
        <div class="provider-label">
          Pane {{ paneIndex + 1 }}
        </div>
        <ProviderDropdown
          :selected-key="sidebar.activeProviders.value[paneIndex] || 'chatgpt'"
          :loading="Boolean(sidebar.providerLoadingByPane.value[paneIndex])"
          @change="(key) => void sidebar.setProvider(paneIndex, key)"
        />
      </div>
    </div>
  </SidebarSection>
</template>

<style scoped>
.provider-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.provider-item {
  display: flex;
  flex-direction: column;
  gap: 6px;
  width: 100%;
}

.provider-label {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.3px;
}
</style>

// src/renderer/sidebar/ProviderList.tsx
import { SidebarSection } from './SidebarSection';
import { useSidebarContext } from './context';
import { ProviderDropdown } from './ProviderDropdown';

export function ProviderList() {
  const sidebar = useSidebarContext();

  return (
    <SidebarSection title="PROVIDERS">
      <div className="provider-list">
        {Array.from({ length: sidebar.paneCount }, (_, paneIndex) => {
          return (
            <div key={paneIndex} className="provider-item">
              <div className="provider-label">Pane {paneIndex + 1}</div>
              <ProviderDropdown
                selectedKey={sidebar.activeProviders[paneIndex] ?? 'chatgpt'}
                loading={Boolean(sidebar.providerLoadingByPane[paneIndex])}
                onChange={(providerKey) => {
                  void sidebar.setProvider(paneIndex, providerKey);
                }}
              />
            </div>
          );
        })}
      </div>
    </SidebarSection>
  );
}
