// src/components/sidebar/Sidebar.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, provide, ref } from 'vue'
import PaneSelector from './PaneSelector.vue'
import ProviderList from './ProviderList.vue'
import PromptComposer from './PromptComposer.vue'
import { MAX_PANES, SIDEBAR_KEY, type PaneCount, type SidebarContext } from './context'
import { APP_CONFIG } from '@/config'
import { resolveSidebarUiDensity } from '@/config/layout'
import { DEFAULT_ACTIVE_PROVIDERS } from '@/providers'
import { getSidebarRuntime } from '@/runtime/sidebar'
import { ACTIVE_THEME_PRESET, getSidebarThemeVars } from '@/theme/palette'

const runtime = getSidebarRuntime()
const SIDEBAR_TOGGLE_SHORTCUT_EVENT = APP_CONFIG.interaction.shortcuts.sidebarToggleEvent
const PROVIDER_LOADING_EVENT = APP_CONFIG.interaction.shortcuts.providerLoadingEvent

const collapsed = ref(false)
const paneCount = ref<PaneCount>(APP_CONFIG.layout.pane.defaultCount as PaneCount)
const activeProviders = ref<string[]>([...DEFAULT_ACTIVE_PROVIDERS])
const providerLoadingByPane = ref<Record<number, boolean>>({})

// Sidebar width from config (loaded on mount)
const expandedWidth = ref<number>(APP_CONFIG.layout.sidebar.defaultExpandedWidth)
const collapsedWidth = APP_CONFIG.layout.sidebar.defaultCollapsedWidth

const configuredSidebarWidth = computed(() =>
  collapsed.value ? collapsedWidth : expandedWidth.value
)
const sidebarWidth = computed(() => `${configuredSidebarWidth.value}px`)
const sidebarStyle = computed(() => ({
  width: sidebarWidth.value,
  ...getSidebarThemeVars(ACTIVE_THEME_PRESET),
}))
const sidebarUiDensity = computed(() => {
  if (collapsed.value) {
    return 'regular'
  }
  return resolveSidebarUiDensity(configuredSidebarWidth.value)
})
const isCompactSidebar = computed(() => sidebarUiDensity.value !== 'regular')
const isTightSidebar = computed(() => sidebarUiDensity.value === 'tight')

const normalizePaneCount = (count: number): PaneCount => {
  const normalized = Math.min(
    MAX_PANES,
    Math.max(APP_CONFIG.layout.pane.minCount, Math.floor(count))
  )
  return normalized as PaneCount
}

// Layout sync
let layoutSyncQueue: Promise<void> = Promise.resolve()
let lastLayoutSignature: string | null = null

const buildLayoutSignature = (
  viewportWidth: number,
  viewportHeight: number,
  panes: PaneCount,
  sidebarW: number
): string => `${viewportWidth}x${viewportHeight}:${panes}:${sidebarW}`

const invalidateLayoutSignature = () => {
  lastLayoutSignature = null
}

const syncLayout = async () => {
  const viewportWidth = Math.max(1, Math.floor(window.innerWidth))
  const viewportHeight = Math.max(1, Math.floor(window.innerHeight))
  const sidebarW = configuredSidebarWidth.value
  const signature = buildLayoutSignature(viewportWidth, viewportHeight, paneCount.value, sidebarW)

  if (signature === lastLayoutSignature) return

  await runtime.updateLayout({
    viewportWidth,
    viewportHeight,
    paneCount: paneCount.value,
    sidebarWidth: sidebarW,
  })
  lastLayoutSignature = signature
}

const syncLayoutWithErrorHandling = async () => {
  layoutSyncQueue = layoutSyncQueue
    .then(() => syncLayout())
    .catch((e) => console.error('[Sidebar] syncLayout error:', e))
  await layoutSyncQueue
}

let resizeRaf = 0
let focusRaf = 0

const focusPromptComposer = async () => {
  if (collapsed.value) return

  await nextTick()
  if (focusRaf !== 0) {
    window.cancelAnimationFrame(focusRaf)
  }
  focusRaf = window.requestAnimationFrame(() => {
    focusRaf = 0
    const textarea = document.querySelector<HTMLTextAreaElement>('[data-testid="prompt-textarea"]')
    if (!textarea || textarea.disabled) return
    textarea.focus()
    const cursorPos = textarea.value.length
    textarea.setSelectionRange(cursorPos, cursorPos)
  })
}

const handleWindowResize = () => {
  if (resizeRaf !== 0) return
  resizeRaf = window.requestAnimationFrame(() => {
    resizeRaf = 0
    void syncLayoutWithErrorHandling()
  })
}

const handleSidebarToggleShortcut = () => {
  void toggleCollapse()
}

const setProviderLoadingState = (paneIndex: number, loading: boolean) => {
  const nextState = { ...providerLoadingByPane.value }
  if (loading) {
    nextState[paneIndex] = true
  } else {
    delete nextState[paneIndex]
  }
  providerLoadingByPane.value = nextState
}

const trimProviderLoadingState = (count: PaneCount) => {
  const nextState: Record<number, boolean> = {}
  for (const [paneIndexRaw, loading] of Object.entries(providerLoadingByPane.value)) {
    const paneIndex = Number(paneIndexRaw)
    if (!Number.isInteger(paneIndex) || paneIndex < 0 || paneIndex >= count || !loading) {
      continue
    }
    nextState[paneIndex] = true
  }
  providerLoadingByPane.value = nextState
}

type ProviderLoadingEventDetail = {
  paneIndex: number
  loading: boolean
}

const handleProviderLoadingEvent = (event: Event) => {
  const detail = (event as CustomEvent<ProviderLoadingEventDetail>).detail
  if (
    !detail ||
    typeof detail.paneIndex !== 'number' ||
    !Number.isInteger(detail.paneIndex) ||
    detail.paneIndex < 0 ||
    typeof detail.loading !== 'boolean'
  ) {
    return
  }

  setProviderLoadingState(detail.paneIndex, detail.loading)
}

onMounted(async () => {
  window.addEventListener('resize', handleWindowResize)
  window.addEventListener(SIDEBAR_TOGGLE_SHORTCUT_EVENT, handleSidebarToggleShortcut)
  window.addEventListener(PROVIDER_LOADING_EVENT, handleProviderLoadingEvent as EventListener)

  try {
    const config = await runtime.getConfig()
    // Load sidebar width from config
    expandedWidth.value = config.sidebar.expanded_width
    if (config.provider.panes.length > 0) {
      activeProviders.value = [...config.provider.panes]
    }
    paneCount.value = normalizePaneCount(config.provider.pane_count)
  } catch (e) {
    console.error('[Sidebar] loadConfig error:', e)
  }

  await syncLayoutWithErrorHandling()
  await focusPromptComposer()
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', handleWindowResize)
  window.removeEventListener(SIDEBAR_TOGGLE_SHORTCUT_EVENT, handleSidebarToggleShortcut)
  window.removeEventListener(PROVIDER_LOADING_EVENT, handleProviderLoadingEvent as EventListener)
  if (resizeRaf !== 0) {
    window.cancelAnimationFrame(resizeRaf)
    resizeRaf = 0
  }
  if (focusRaf !== 0) {
    window.cancelAnimationFrame(focusRaf)
    focusRaf = 0
  }
})

const toggleCollapse = async () => {
  collapsed.value = !collapsed.value
  await syncLayoutWithErrorHandling()
  if (!collapsed.value) {
    await focusPromptComposer()
  }
}

const setPaneCount = async (count: number) => {
  const oldCount = paneCount.value
  const newCount = normalizePaneCount(count)
  if (newCount === oldCount) return
  paneCount.value = newCount

  try {
    await runtime.setPaneCount(newCount)
    trimProviderLoadingState(newCount)
  } catch (e) {
    invalidateLayoutSignature()
    paneCount.value = oldCount
    trimProviderLoadingState(oldCount)
    console.error('[Sidebar] setPaneCount error:', e)
  }
}

const setProvider = async (paneIndex: number, providerKey: string) => {
  if (activeProviders.value[paneIndex] === providerKey) return

  try {
    await runtime.updateProvider(paneIndex, providerKey)
    activeProviders.value[paneIndex] = providerKey
  } catch (e) {
    setProviderLoadingState(paneIndex, false)
    console.error('[Sidebar] setProvider error:', e)
  }
}

const sendPrompt = async (text: string) => {
  try {
    await runtime.sendPrompt(text)
  } catch (e) {
    console.error('[Sidebar] sendPrompt error:', e)
    throw e
  }
}

const syncPromptDraft = async (text: string) => {
  try {
    await runtime.syncPromptDraft(text)
  } catch (e) {
    // Draft syncing is best-effort and should not break typing flow.
    console.error('[Sidebar] syncPromptDraft error:', e)
  }
}

const sidebarContext: SidebarContext = {
  paneCount,
  activeProviders,
  providerLoadingByPane,
  setPaneCount,
  setProvider,
  syncPromptDraft,
  sendPrompt,
}

provide(SIDEBAR_KEY, sidebarContext)
</script>

<template>
  <aside
    class="sidebar"
    :class="{
      collapsed,
      'is-compact': isCompactSidebar,
      'is-tight': isTightSidebar
    }"
    :style="sidebarStyle"
    data-testid="sidebar"
  >
    <div class="sidebar-header">
      <span class="sidebar-title" data-testid="sidebar-title">LAZY LLM</span>
      <button
        class="collapse-btn"
        title="Toggle sidebar (Ctrl+B)"
        data-testid="sidebar-collapse"
        @click="void toggleCollapse()"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="11 17 6 12 11 7"></polyline>
          <polyline points="18 17 13 12 18 7"></polyline>
        </svg>
      </button>
    </div>

    <div class="sidebar-content" data-testid="sidebar-content">
      <div class="sidebar-scroll" data-testid="sidebar-scroll">
        <PaneSelector />
        <ProviderList />
        <PromptComposer />
      </div>
    </div>
  </aside>
</template>

<style scoped>
.sidebar {
  height: 100%;
  display: flex;
  flex-direction: column;
  padding: 12px;
  background: var(--bg);
  border-right: 1px solid var(--border);
  box-sizing: border-box;
  flex-shrink: 0;
  position: relative;
  z-index: 10;
}

.sidebar.is-compact {
  padding: 10px;
}

.sidebar.is-tight {
  padding: 8px;
}

.sidebar.collapsed {
  padding: 8px 0;
  align-items: center;
}

.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding-bottom: 16px;
  border-bottom: 1px solid var(--border);
  margin-bottom: 16px;
  -webkit-app-region: drag;
}

.sidebar.is-compact .sidebar-header {
  gap: 6px;
  padding-bottom: 12px;
  margin-bottom: 12px;
}

.sidebar.is-tight .sidebar-header {
  gap: 4px;
  padding-bottom: 10px;
  margin-bottom: 10px;
}

.sidebar.collapsed .sidebar-header {
  width: 100%;
  border-bottom: none;
  padding-bottom: 0;
  margin-bottom: 0;
  justify-content: center;
}

.sidebar-title {
  font-size: 14px;
  font-weight: 700;
  letter-spacing: 0.5px;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.sidebar.is-compact .sidebar-title {
  font-size: 13px;
  letter-spacing: 0.35px;
}

.sidebar.is-tight .sidebar-title {
  font-size: 12px;
  letter-spacing: 0.2px;
}

.sidebar.collapsed .sidebar-title {
  display: none;
}

.collapse-btn {
  width: 24px;
  height: 24px;
  border: none;
  background: transparent;
  color: var(--text-muted);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 4px;
  transition: background 0.15s, color 0.15s;
  -webkit-app-region: no-drag;
}

.collapse-btn:hover {
  background: var(--bg-hover);
  color: var(--text);
}

.collapse-btn svg {
  width: 16px;
  height: 16px;
  transition: transform 0.2s;
}

.sidebar.is-compact .collapse-btn {
  width: 22px;
  height: 22px;
}

.sidebar.is-tight .collapse-btn {
  width: 20px;
  height: 20px;
}

.sidebar.collapsed .collapse-btn {
  width: 28px;
  height: 28px;
}

.sidebar.collapsed .collapse-btn svg {
  transform: rotate(180deg);
}

.sidebar-content {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-height: 0;
}

.sidebar-scroll {
  height: 100%;
  overflow-y: auto;
  overflow-x: hidden;
  padding-right: 2px;
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.sidebar.is-compact .sidebar-scroll {
  padding-right: 1px;
}

.sidebar.is-tight .sidebar-scroll {
  padding-right: 0;
}

.sidebar-scroll::-webkit-scrollbar {
  width: 8px;
}

.sidebar-scroll::-webkit-scrollbar-thumb {
  background: var(--sidebar-scrollbar-thumb);
  border-radius: 8px;
}

.sidebar-scroll::-webkit-scrollbar-thumb:hover {
  background: var(--sidebar-scrollbar-thumb-hover);
}

.sidebar.collapsed .sidebar-content {
  display: none;
}

.sidebar.is-compact :deep(.section) {
  margin-bottom: 16px;
}

.sidebar.is-tight :deep(.section) {
  margin-bottom: 12px;
}

.sidebar.is-compact :deep(.section-title) {
  font-size: 11px;
  margin-bottom: 9px;
  letter-spacing: 0.55px;
  gap: 6px;
}

.sidebar.is-tight :deep(.section-title) {
  font-size: 10px;
  margin-bottom: 7px;
  letter-spacing: 0.4px;
  gap: 4px;
}

.sidebar.is-tight :deep(.section-title::before) {
  height: 10px;
}

.sidebar.is-compact :deep(.pane-toggle) {
  gap: 6px;
}

.sidebar.is-tight :deep(.pane-toggle) {
  gap: 4px;
}

.sidebar.is-compact :deep(.chip) {
  padding: 7px 4px;
  font-size: 13px;
  border-radius: 7px;
}

.sidebar.is-tight :deep(.chip) {
  padding: 6px 3px;
  font-size: 12px;
  border-radius: 6px;
}

.sidebar.is-compact :deep(.provider-list) {
  gap: 9px;
}

.sidebar.is-tight :deep(.provider-list) {
  gap: 7px;
}

.sidebar.is-compact :deep(.provider-item) {
  gap: 5px;
}

.sidebar.is-tight :deep(.provider-item) {
  gap: 4px;
}

.sidebar.is-compact :deep(.provider-label) {
  font-size: 12px;
}

.sidebar.is-tight :deep(.provider-label) {
  font-size: 11px;
  letter-spacing: 0.2px;
}

.sidebar.is-compact :deep(.select-trigger) {
  padding: 8px 10px;
  font-size: 14px;
  border-radius: 8px;
}

.sidebar.is-tight :deep(.select-trigger) {
  padding: 7px 9px;
  font-size: 13px;
  border-radius: 7px;
}

.sidebar.is-compact :deep(.trigger-content) {
  gap: 8px;
}

.sidebar.is-tight :deep(.trigger-content) {
  gap: 6px;
}

.sidebar.is-compact :deep(.dropdown-item) {
  gap: 8px;
  padding: 8px;
  font-size: 14px;
}

.sidebar.is-tight :deep(.dropdown-item) {
  gap: 6px;
  padding: 7px;
  font-size: 13px;
}

.sidebar.is-compact :deep(.composer-section) {
  margin-top: 10px;
  padding-top: 12px;
}

.sidebar.is-tight :deep(.composer-section) {
  margin-top: 8px;
  padding-top: 10px;
}

.sidebar.is-compact :deep(.composer-textarea) {
  padding: 12px 13px;
  font-size: 14px;
  margin-bottom: 8px;
}

.sidebar.is-tight :deep(.composer-textarea) {
  padding: 10px 11px;
  font-size: 13px;
  margin-bottom: 7px;
}

.sidebar.is-compact :deep(.composer-shortcut-hint) {
  font-size: 12px;
  margin-bottom: 8px;
}

.sidebar.is-tight :deep(.composer-shortcut-hint) {
  font-size: 11px;
  margin-bottom: 7px;
}

.sidebar.is-compact :deep(.composer-send-btn) {
  padding: 10px 12px;
  font-size: 13px;
}

.sidebar.is-tight :deep(.composer-send-btn) {
  padding: 9px 10px;
  font-size: 12px;
}
</style>

// src/renderer/sidebar/Sidebar.tsx
import {
  type CSSProperties,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { APP_CONFIG } from '@/config';
import { resolveSidebarUiDensity } from '@/config/layout';
import { getSidebarRuntime } from '@/runtime/sidebar';
import { ACTIVE_THEME_PRESET, getSidebarThemeVars } from '@/theme/palette';
import { PaneSelector } from './PaneSelector';
import { ProviderList } from './ProviderList';
import { PromptComposer } from './PromptComposer';
import { type PaneCount, SidebarContextProvider } from './context';
import { resolveStartupState, saveUiSettings } from '../state/uiSettings';

const SIDEBAR_TOGGLE_SHORTCUT_EVENT = APP_CONFIG.interaction.shortcuts.sidebarToggleEvent;
const PROVIDER_LOADING_EVENT = APP_CONFIG.interaction.shortcuts.providerLoadingEvent;

function normalizePaneCount(count: number): PaneCount {
  const normalized = Math.min(
    APP_CONFIG.layout.pane.maxCount,
    Math.max(APP_CONFIG.layout.pane.minCount, Math.floor(count)),
  );
  return normalized as PaneCount;
}

const providerKeySet: Set<string> = new Set(
  APP_CONFIG.providers.catalog.map((provider) => provider.key),
);
const fallbackProvider = APP_CONFIG.providers.defaultPaneKeys[0] ?? 'chatgpt';

function normalizeProviderSequence(providers: readonly string[], paneCount: PaneCount): string[] {
  const firstProvider = providers[0] && providerKeySet.has(providers[0])
    ? providers[0]
    : fallbackProvider;

  return Array.from({ length: paneCount }, (_, paneIndex) => {
    const candidate = providers[paneIndex];
    if (typeof candidate === 'string' && providerKeySet.has(candidate)) {
      return candidate;
    }
    return firstProvider;
  });
}

export function Sidebar() {
  const runtime = useMemo(() => getSidebarRuntime(), []);

  const [collapsed, setCollapsed] = useState(false);
  const [paneCount, setPaneCountState] = useState<PaneCount>(
    APP_CONFIG.layout.pane.defaultCount as PaneCount,
  );
  const [activeProviders, setActiveProviders] = useState<string[]>([
    ...APP_CONFIG.providers.defaultActiveKeys,
  ]);
  const [providerLoadingByPane, setProviderLoadingByPane] = useState<Record<number, boolean>>({});
  const [expandedWidth, setExpandedWidth] = useState<number>(
    APP_CONFIG.layout.sidebar.defaultExpandedWidth,
  );

  const collapsedRef = useRef(collapsed);
  const paneCountRef = useRef(paneCount);
  const activeProvidersRef = useRef(activeProviders);
  const expandedWidthRef = useRef(expandedWidth);

  useEffect(() => {
    collapsedRef.current = collapsed;
  }, [collapsed]);

  useEffect(() => {
    paneCountRef.current = paneCount;
  }, [paneCount]);

  useEffect(() => {
    activeProvidersRef.current = activeProviders;
  }, [activeProviders]);

  useEffect(() => {
    expandedWidthRef.current = expandedWidth;
  }, [expandedWidth]);

  const collapsedWidth = APP_CONFIG.layout.sidebar.defaultCollapsedWidth;
  const sidebarTransitionDurationMs = APP_CONFIG.layout.sidebar.transitionDurationMs;
  const isElectronRuntime = typeof window !== 'undefined' && typeof window.council !== 'undefined';

  const configuredSidebarWidth = collapsed ? collapsedWidth : expandedWidth;

  const sidebarUiDensity = collapsed ? 'regular' : resolveSidebarUiDensity(configuredSidebarWidth);
  const isCompactSidebar = sidebarUiDensity !== 'regular';
  const isTightSidebar = sidebarUiDensity === 'tight';

  const layoutSyncQueueRef = useRef<Promise<void>>(Promise.resolve());
  const lastLayoutSignatureRef = useRef<string | null>(null);
  const resizeRafRef = useRef(0);
  const focusRafRef = useRef(0);

  const persistUiSettings = useCallback((overrides?: {
    paneCount?: PaneCount;
    paneProviders?: string[];
    sidebarWidth?: number;
  }) => {
    saveUiSettings({
      version: 1,
      layout: {
        paneCount: overrides?.paneCount ?? paneCountRef.current,
        sidebarWidth: overrides?.sidebarWidth ?? expandedWidthRef.current,
      },
      providers: {
        paneKeys: overrides?.paneProviders ?? activeProvidersRef.current,
      },
    });
  }, []);

  const buildLayoutSignature = useCallback((panes: PaneCount, sidebarWidth: number): string => {
    return `${panes}:${sidebarWidth}`;
  }, []);

  const invalidateLayoutSignature = useCallback(() => {
    lastLayoutSignatureRef.current = null;
  }, []);

  const syncLayout = useCallback(async () => {
    const panes = paneCountRef.current;
    const sidebarWidth = collapsedRef.current ? collapsedWidth : expandedWidthRef.current;
    const viewportWidth = Math.max(1, Math.floor(window.innerWidth));
    const viewportHeight = Math.max(1, Math.floor(window.innerHeight));

    const signature = buildLayoutSignature(panes, sidebarWidth);
    if (signature === lastLayoutSignatureRef.current) {
      return;
    }

    await runtime.updateLayout({
      viewportWidth,
      viewportHeight,
      paneCount: panes,
      sidebarWidth,
    });

    lastLayoutSignatureRef.current = signature;
  }, [buildLayoutSignature, collapsedWidth, runtime]);

  const enqueueLayoutSync = useCallback(async () => {
    layoutSyncQueueRef.current = layoutSyncQueueRef.current
      .then(() => syncLayout())
      .catch((error) => {
        console.error('[Sidebar] syncLayout error:', error);
      });

    await layoutSyncQueueRef.current;
  }, [syncLayout]);

  const focusPromptComposer = useCallback(async () => {
    if (collapsedRef.current) {
      return;
    }

    if (focusRafRef.current !== 0) {
      window.cancelAnimationFrame(focusRafRef.current);
      focusRafRef.current = 0;
    }

    await new Promise<void>((resolve) => {
      focusRafRef.current = window.requestAnimationFrame(() => {
        focusRafRef.current = 0;

        const textarea = document.querySelector<HTMLTextAreaElement>('textarea.composer-textarea');
        if (textarea && !textarea.disabled) {
          textarea.focus();
          const cursorPosition = textarea.value.length;
          textarea.setSelectionRange(cursorPosition, cursorPosition);
        }

        resolve();
      });
    });
  }, []);

  const trimProviderLoadingState = useCallback((count: PaneCount) => {
    setProviderLoadingByPane((current) => {
      const next: Record<number, boolean> = {};
      for (const [paneIndexRaw, loading] of Object.entries(current)) {
        const paneIndex = Number(paneIndexRaw);
        if (!Number.isInteger(paneIndex) || paneIndex < 0 || paneIndex >= count || !loading) {
          continue;
        }
        next[paneIndex] = true;
      }
      return next;
    });
  }, []);

  const setProviderLoadingState = useCallback((paneIndex: number, loading: boolean) => {
    setProviderLoadingByPane((current) => {
      const next = { ...current };
      if (loading) {
        next[paneIndex] = true;
      } else {
        delete next[paneIndex];
      }
      return next;
    });
  }, []);

  const toggleCollapse = useCallback(async () => {
    const nextCollapsed = !collapsedRef.current;
    collapsedRef.current = nextCollapsed;
    setCollapsed(nextCollapsed);

    await enqueueLayoutSync();

    if (!nextCollapsed) {
      await focusPromptComposer();
    }
  }, [enqueueLayoutSync, focusPromptComposer]);

  const setPaneCount = useCallback(
    async (count: number) => {
      const oldCount = paneCountRef.current;
      const oldProviders = normalizeProviderSequence(activeProvidersRef.current, oldCount);

      const newCount = normalizePaneCount(count);
      if (newCount === oldCount) {
        return;
      }

      const nextProviders = normalizeProviderSequence(activeProvidersRef.current, newCount);

      paneCountRef.current = newCount;
      setPaneCountState(newCount);
      activeProvidersRef.current = nextProviders;
      setActiveProviders(nextProviders);

      try {
        await runtime.setPaneCount(newCount);
        trimProviderLoadingState(newCount);
        persistUiSettings({
          paneCount: newCount,
          paneProviders: nextProviders,
        });
      } catch (error) {
        invalidateLayoutSignature();
        paneCountRef.current = oldCount;
        setPaneCountState(oldCount);
        activeProvidersRef.current = oldProviders;
        setActiveProviders(oldProviders);
        trimProviderLoadingState(oldCount);
        console.error('[Sidebar] setPaneCount error:', error);
      }

      await enqueueLayoutSync();
    },
    [enqueueLayoutSync, invalidateLayoutSignature, persistUiSettings, runtime, trimProviderLoadingState],
  );

  const newAll = useCallback(async () => {
    try {
      await runtime.resetAllPanes();
    } catch (error) {
      console.error('[Sidebar] newAll error:', error);
    }
  }, [runtime]);

  const setProvider = useCallback(
    async (paneIndex: number, providerKey: string) => {
      if (activeProvidersRef.current[paneIndex] === providerKey) {
        return;
      }

      try {
        await runtime.updateProvider(paneIndex, providerKey);

        const nextProviders = normalizeProviderSequence(activeProvidersRef.current, paneCountRef.current);
        nextProviders[paneIndex] = providerKey;
        activeProvidersRef.current = nextProviders;
        setActiveProviders(nextProviders);

        persistUiSettings({
          paneProviders: nextProviders,
        });
      } catch (error) {
        setProviderLoadingState(paneIndex, false);
        console.error('[Sidebar] setProvider error:', error);
      }
    },
    [persistUiSettings, runtime, setProviderLoadingState],
  );

  const sendPrompt = useCallback(
    async (text: string) => {
      try {
        await runtime.sendPrompt(text);
      } catch (error) {
        console.error('[Sidebar] sendPrompt error:', error);
        throw error;
      }
    },
    [runtime],
  );

  const syncPromptDraft = useCallback(
    async (text: string) => {
      try {
        await runtime.syncPromptDraft(text);
      } catch (error) {
        console.error('[Sidebar] syncPromptDraft error:', error);
      }
    },
    [runtime],
  );

  useEffect(() => {
    const handleWindowResize = () => {
      if (resizeRafRef.current !== 0) {
        return;
      }

      resizeRafRef.current = window.requestAnimationFrame(() => {
        resizeRafRef.current = 0;
        void enqueueLayoutSync();
      });
    };

    const handleSidebarToggleShortcut = () => {
      void toggleCollapse();
    };

    const handleProviderLoadingEvent = (event: Event) => {
      const detail = (event as CustomEvent<{ paneIndex: number; loading: boolean }>).detail;
      if (
        !detail ||
        typeof detail.paneIndex !== 'number' ||
        !Number.isInteger(detail.paneIndex) ||
        detail.paneIndex < 0 ||
        typeof detail.loading !== 'boolean'
      ) {
        return;
      }

      setProviderLoadingState(detail.paneIndex, detail.loading);
    };

    let active = true;

    const initialize = async () => {
      try {
        const config = await runtime.getConfig();
        const startupState = resolveStartupState(config);

        if (!active) {
          return;
        }

        setExpandedWidth(startupState.sidebarWidth);
        expandedWidthRef.current = startupState.sidebarWidth;

        setPaneCountState(startupState.paneCount);
        paneCountRef.current = startupState.paneCount;

        setActiveProviders(startupState.paneProviders);
        activeProvidersRef.current = startupState.paneProviders;

        if (startupState.paneCount !== config.provider.pane_count) {
          await runtime.setPaneCount(startupState.paneCount);
        }

        for (let paneIndex = 0; paneIndex < startupState.paneCount; paneIndex += 1) {
          const targetProvider = startupState.paneProviders[paneIndex];
          const currentProvider = config.provider.panes[paneIndex];

          if (targetProvider !== currentProvider) {
            await runtime.updateProvider(paneIndex, targetProvider);
          }
        }

        persistUiSettings({
          paneCount: startupState.paneCount,
          paneProviders: startupState.paneProviders,
          sidebarWidth: startupState.sidebarWidth,
        });
      } catch (error) {
        console.error('[Sidebar] initialize error:', error);
      }

      if (!active) {
        return;
      }

      await enqueueLayoutSync();
      await focusPromptComposer();
    };

    window.addEventListener('resize', handleWindowResize);
    window.addEventListener(SIDEBAR_TOGGLE_SHORTCUT_EVENT, handleSidebarToggleShortcut);
    window.addEventListener(PROVIDER_LOADING_EVENT, handleProviderLoadingEvent as EventListener);

    void initialize();

    return () => {
      active = false;
      window.removeEventListener('resize', handleWindowResize);
      window.removeEventListener(SIDEBAR_TOGGLE_SHORTCUT_EVENT, handleSidebarToggleShortcut);
      window.removeEventListener(PROVIDER_LOADING_EVENT, handleProviderLoadingEvent as EventListener);

      if (resizeRafRef.current !== 0) {
        window.cancelAnimationFrame(resizeRafRef.current);
        resizeRafRef.current = 0;
      }

      if (focusRafRef.current !== 0) {
        window.cancelAnimationFrame(focusRafRef.current);
        focusRafRef.current = 0;
      }
    };
  }, [enqueueLayoutSync, focusPromptComposer, persistUiSettings, runtime, setProviderLoadingState, toggleCollapse]);

  const sidebarStyle = useMemo(() => {
    return {
      width: isElectronRuntime ? '100%' : `${configuredSidebarWidth}px`,
      '--sidebar-transition-duration': `${sidebarTransitionDurationMs}ms`,
      ...getSidebarThemeVars(ACTIVE_THEME_PRESET),
    } as CSSProperties;
  }, [configuredSidebarWidth, isElectronRuntime, sidebarTransitionDurationMs]);

  const contextValue = useMemo(() => {
    return {
      paneCount,
      activeProviders,
      providerLoadingByPane,
      setPaneCount,
      newAll,
      setProvider,
      syncPromptDraft,
      sendPrompt,
    };
  }, [activeProviders, newAll, paneCount, providerLoadingByPane, sendPrompt, setPaneCount, setProvider, syncPromptDraft]);

  return (
    <SidebarContextProvider value={contextValue}>
      <aside
        className={`sidebar${collapsed ? ' collapsed' : ''}${isCompactSidebar ? ' is-compact' : ''}${isTightSidebar ? ' is-tight' : ''}`}
        style={sidebarStyle}
      >
        <div className="sidebar-header">
          <span className="sidebar-title">LAZY LLM</span>
          <button
            type="button"
            className="collapse-btn"
            title="Toggle sidebar (Ctrl+B)"
            onClick={() => {
              void toggleCollapse();
            }}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <polyline points="11 17 6 12 11 7" />
              <polyline points="18 17 13 12 18 7" />
            </svg>
          </button>
        </div>

        <div className="sidebar-content">
          <div className="sidebar-scroll">
            <PaneSelector />
            <ProviderList />
            <PromptComposer />
          </div>
        </div>
      </aside>
    </SidebarContextProvider>
  );
}
